#!/usr/bin/env bash
#
# Regenerate the Homebrew formula in donald-jackson/homebrew-tap from a published
# release, and push it.
#
# The checksums come from the release's own checksums.txt rather than being recomputed
# here, so the formula can only ever attest to what was actually published. Run it after
# a release finishes:
#
#   scripts/update-tap.sh v0.2.0
#
# Authentication is gh's own credentials locally, or TAP_TOKEN in CI (the default
# GITHUB_TOKEN cannot write to another repository).
set -euo pipefail

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
  echo "usage: $(basename "$0") vX.Y.Z" >&2
  exit 2
fi
case "$VERSION" in
  v*) ;;
  *) echo "version must start with 'v' (got '$VERSION')" >&2; exit 2 ;;
esac

REPO="${REPO:-donald-jackson/openrouter-fusion-cli}"
TAP_REPO="${TAP_REPO:-donald-jackson/homebrew-tap}"
# Homebrew derives the formula name from the filename, so this must stay "council.rb".
FORMULA_PATH="Formula/council.rb"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "==> fetching checksums for $VERSION"
gh release download "$VERSION" --repo "$REPO" --pattern checksums.txt --dir "$work"

sha_for() {
  local asset="council_${VERSION}_$1.tar.gz"
  local sum
  sum="$(awk -v a="$asset" '$2 == a || $2 == "*"a {print $1}' "$work/checksums.txt")"
  if [ -z "$sum" ]; then
    echo "no checksum for $asset in the release" >&2
    exit 1
  fi
  echo "$sum"
}

DARWIN_ARM64="$(sha_for darwin_arm64)"
DARWIN_AMD64="$(sha_for darwin_amd64)"
LINUX_AMD64="$(sha_for linux_amd64)"
LINUX_ARM64="$(sha_for linux_arm64)"

# Homebrew's "version" is the bare number; the tag keeps its v prefix.
BARE="${VERSION#v}"
DL="https://github.com/${REPO}/releases/download/${VERSION}"

echo "==> cloning $TAP_REPO"
if [ -n "${TAP_TOKEN:-}" ]; then
  git clone --depth 1 "https://x-access-token:${TAP_TOKEN}@github.com/${TAP_REPO}.git" "$work/tap"
else
  gh repo clone "$TAP_REPO" "$work/tap" -- --depth 1
fi

mkdir -p "$work/tap/$(dirname "$FORMULA_PATH")"
cat > "$work/tap/$FORMULA_PATH" <<FORMULA
# Generated by scripts/update-tap.sh in ${REPO}. Do not edit by hand:
# the next release will overwrite it.
class Council < Formula
  desc "Ask frontier models one question and see where they disagree"
  homepage "https://github.com/${REPO}"
  version "${BARE}"

  # There is no single top-level url for livecheck to follow, so it watches the
  # repository's releases directly.
  livecheck do
    url :homepage
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "${DL}/council_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM64}"
    end
    on_intel do
      url "${DL}/council_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${DARWIN_AMD64}"
    end
  end

  on_linux do
    on_arm do
      url "${DL}/council_${VERSION}_linux_arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
    on_intel do
      url "${DL}/council_${VERSION}_linux_amd64.tar.gz"
      sha256 "${LINUX_AMD64}"
    end
  end

  def install
    bin.install "council"
  end

  def caveats
    <<~EOS
      Store your OpenRouter API key before the first consultation:

        council setup

      It prompts without echoing, verifies the key, and writes it to
      ~/.config/council/config.env with mode 0600.
    EOS
  end

  test do
    # Version, so a mismatched or truncated download fails the test.
    assert_match "council #{version}", shell_output("#{bin}/council version")

    # Discovery against the live catalog endpoint, which needs no credentials. This
    # is the check that the binary actually runs on this machine rather than merely
    # existing, and it must not require an API key to pass.
    assert_match "OpenAI", shell_output("#{bin}/council models")

    # A consultation without a key must fail cleanly with exit 3, not hang or panic.
    output = shell_output("OPENROUTER_API_KEY= #{bin}/council ask 'x' 2>&1", 3)
    assert_match "OPENROUTER_API_KEY", output
  end
end
FORMULA

cd "$work/tap"
if git diff --quiet -- "$FORMULA_PATH"; then
  echo "==> formula already up to date"
  exit 0
fi

git add "$FORMULA_PATH"
git -c user.name="${GIT_NAME:-Donald Jackson}" \
    -c user.email="${GIT_EMAIL:-donald@ddj.co.za}" \
    commit -q -m "council ${BARE}"
git push -q origin HEAD
echo "==> pushed council ${BARE} to ${TAP_REPO}"
